In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [50]:
movie=pd.read_csv("2016년여가겨일별데이터_정리.csv", engine='python')
movie=movie.dropna()

In [51]:
movie_peo=pd.DataFrame(movie['누적관객수'].groupby(movie['영화명']).max())
movie_peo=movie_peo.reset_index()
movie_peo=movie_peo.where(movie_peo['누적관객수']>10000).dropna()
movie_peo

                       영화명      누적관객수
10                   21 그램    64551.0
11                23 아이덴티티  1316094.0
14                   45년 후    23940.0
15                      4등    38692.0
16                500일의 썸머   285391.0
17            50가지 그림자: 심연   188625.0
18                  5일의 마중    54843.0
20               60만번의 트라이    21432.0
22            7년-그들이 없는 언론    16888.0
27                  MB의 추억    14961.0
34                  가려진 시간   510878.0
36              가부와 메이 이야기   251875.0
42            가장 따뜻한 색, 블루    52596.0
52                 감바의 대모험   117591.0
56             갓파 쿠와 여름방학을    38202.0
60           개를 훔치는 완벽한 방법   306642.0
62      갤럭시 히어로즈: 라쳇 앤 클랭크    46793.0
65               거울나라의 앨리스   513202.0
71                      거인    23979.0
76                     걷기왕    95542.0
78                 걸어도 걸어도    32627.0
79             걸즈 앤 판처 극장판    28785.0
80                    검사외전  9707581.0
81                    검우강호   312334.0
82                  검은 사제들  5442915.0
95                    계춘할망   482516.0
96    고녀석 맛나겠다2 : 함께라서 행복해    55922.0
99                      고백    43511.0
100             고산자, 대동여지도   974262.0
103                고스트버스터즈   515553.0
...                    ...        ...
1998               하드코어 헨리    46373.0
2000                  하류인생   224856.0
2010           하이큐!! 끝과 시작    75704.0
2011          하이큐!! 승자와 패자    37329.0
2015                   한공주   225581.0
2017             한여름의 판타지아    36754.0
2023        해리 포터와 죽음의 성물1  2853500.0
2024         해리가 샐리를 만났을 때    19592.0
2025         해리포터와 죽음의 성물2  4421210.0
2026                  해바라기    10077.0
2027                    해빙   389152.0
2028                   해어화   485695.0
2032                 핵소 고지   152375.0
2037                행복한 사전    15515.0
2038      향수 : 어느 살인자의 이야기   979328.0
2044                 헤이트풀8   121288.0
2045               헤일, 시저!    34331.0
2051                     형  2982022.0
2054           형사; Duelist   922680.0
2058   호두까기 인형: 장난감 왕국 대모험    12542.0
2059             호두까기인형 3D    46815.0
2060          호비와 동화나라 대모험    16620.0
2061                  호우시절   287857.0
2062                    혼숨   288016.0
2069                  화양연화    12279.0
2071                    화장   142609.0
2072                    화차  2436810.0
2073                 환상의 빛    19281.0
2080               후회하지 않아    42029.0
2091                  히말라야  7759761.0

[641 rows x 2 columns]

In [52]:
mergemovie=pd.merge(movie_peo,movie,on='영화명')

In [53]:
mergemovie

,영화명,누적관객수_x,개봉일,날짜,매출액점유율,관객수,누적관객수_y,개봉후일수
0,21 그램,64551.0,2004-10-23,2017-01-20,0.000,18,64457,4472
1,21 그램,64551.0,2004-10-23,2017-01-29,0.000,40,64497,4481
2,21 그램,64551.0,2004-10-23,2017-02-15,0.000,54,64551,4498
3,23 아이덴티티,1316094.0,2017-02-22,2017-02-14,0.001,274,274,-8
4,23 아이덴티티,1316094.0,2017-02-22,2017-02-22,0.237,137005,137279,0
5,23 아이덴티티,1316094.0,2017-02-22,2017-03-01,0.115,119402,1316094,7
6,23 아이덴티티,1316094.0,2017-02-22,2017-02-28,0.242,116555,1196692,6
7,23 아이덴티티,1316094.0,2017-02-22,2017-02-27,0.317,113233,1080137,5
8,23 아이덴티티,1316094.0,2017-02-22,2017-02-26,0.337,265101,966904,4
9,23 아이덴티티,1316094.0,2017-02-22,2017-02-25,0.341,283621,701803,3
10,23 아이덴티티,1316094.0,2017-02-22,2017-02-24,0.327,150119,418182,2
11,23 아이덴티티,1316094.0,2017-02-22,2017-02-23,0.306,130784,268063,1
12,45년 후,23940.0,2016-05-05,2016-06-07,0.000,49,23122,33
13,45년 후,23940.0,2016-05-05,2016-06-06,0.000,154,23073,32
14,45년 후,23940.0,2016-05-05,2016-06-05,0.000,141,22919,31
15,45년 후,23940.0,2016-05-05,2016-06-04,0.000,163,22778,30
16,45년 후,23940.0,2016-05-05,2016-06-03,0.000,102,22615,29
17,45년 후,23940.0,2016-05-05,2016-06-02,0.000,100,22513,28
18,45년 후,23940.0,2016-05-05,2016-06-01,0.000,66,22413,27
19,45년 후,23940.0,2016-05-05,2016-06-13,0.000,8,23598,39
20,45년 후,23940.0,2016-05-05,2016-06-12,0.000,73,23590,38
21,45년 후,23940.0,2016-05-05,2016-06-11,0.000,41,23517,37
22,45년 후,23940.0,2016-05-05,2016-06-10,0.000,37,23476,36
23,45년 후,23940.0,2016-05-05,2016-06-09,0.000,213,23439,35
24,45년 후,23940.0,2016-05-05,2016-06-08,0.000,104,23226,34
25,45년 후,23940.0,2016-05-05,2016-06-21,0.000,9,23741,47
26,45년 후,23940.0,2016-05-05,2016-06-19,0.000,6,23732,45
27,45년 후,23940.0,2016-05-05,2016-06-18,0.000,48,23726,44
28,45년 후,23940.0,2016-05-05,2016-06-17,0.000,30,23678,43
29,45년 후,23940.0,2016-05-05,2016-06-15,0.000,50,23648,41
...,...,...,...,...,...,...,...,...
16283,환상의 빛,19281.0,2016-07-07,2016-08-07,0.000,186,17467,31
16284,환상의 빛,19281.0,2016-07-07,2016-08-06,0.000,199,17281,30
16285,환상의 빛,19281.0,2016-07-07,2016-08-05,0.000,105,17082,29
16286,환상의 빛,19281.0,2016-07-07,2016-08-04,0.000,95,16977,28
16287,환상의 빛,19281.0,2016-07-07,2016-08-03,0.000,158,16882,27
16288,환상의 빛,19281.0,2016-07-07,2016-08-16,0.000,96,18633,40
16289,환상의 빛,19281.0,2016-07-07,2016-08-15,0.000,169,18537,39
16290,환상의 빛,19281.0,2016-07-07,2016-08-14,0.000,214,18368,38
16291,환상의 빛,19281.0,2016-07-07,2016-08-13,0.000,203,18154,37
16292,환상의 빛,19281.0,2016-07-07,2016-08-12,0.000,79,17951,36
16293,환상의 빛,19281.0,2016-07-07,2016-08-11,0.000,129,17872,35
16294,환상의 빛,19281.0,2016-07-07,2016-08-10,0.000,145,17743,34
16295,환상의 빛,19281.0,2016-07-07,2016-08-23,0.000,48,19187,47
16296,환상의 빛,19281.0,2016-07-07,2016-08-22,0.000,12,19139,46
16297,환상의 빛,19281.0,2016-07-07,2016-08-21,0.000,65,19127,45
16298,환상의 빛,19281.0,2016-07-07,2016-08-20,0.000,218,19062,44
16299,환상의 빛,19281.0,2016-07-07,2016-08-19,0.000,39,18844,43
16300,환상의 빛,19281.0,2016-07-07,2016-08-18,0.000,64,18805,42
16301,환상의 빛,19281.0,2016-07-07,2016-08-17,0.000,108,18741,41
16302,환상의 빛,19281.0,2016-07-07,2016-08-30,0.000,13,19241,54
16303,환상의 빛,19281.0,2016-07-07,2016-08-29,0.000,20,19228,53
16304,환상의 빛,19281.0,2016-07-07,2016-08-24,0.000,21,19208,48
16305,환상의 빛,19281.0,2016-07-07,2016-08-31,0.000,15,19256,55
16306,환상의 빛,19281.0,2016-07-07,2016-12-02,0.000,6,19262,148
16307,환상의 빛,19281.0,2016-07-07,2017-01-08,0.000,12,19281,185
16308,환상의 빛,19281.0,2016-07-07,2017-01-07,0.000,7,19269,184
16309,후회하지 않아,42029.0,2006-11-16,2016-11-12,0.000,67,42029,3649
16310,히말라야,7759761.0,2015-12-16,2016-06-01,0.000,0,7759709,168
16311,히말라야,7759761.0,2015-12-16,2016-07-02,0.000,0,7759709,199
16312,히말라야,7759761.0,2015-12-16,2016-12-04,0.000,52,7759761,354

In [54]:
movie_name=pd.DataFrame(mergemovie['영화명'])
movie_name=movie_name.drop_duplicates()
movie_name

                        영화명
0                     21 그램
3                  23 아이덴티티
12                    45년 후
39                       4등
92                 500일의 썸머
172            50가지 그림자: 심연
194                  5일의 마중
201               60만번의 트라이
202            7년-그들이 없는 언론
260                  MB의 추억
261                  가려진 시간
315              가부와 메이 이야기
321            가장 따뜻한 색, 블루
330                 감바의 대모험
393             갓파 쿠와 여름방학을
401           개를 훔치는 완벽한 방법
404      갤럭시 히어로즈: 라쳇 앤 클랭크
447               거울나라의 앨리스
498                      거인
501                     걷기왕
560                 걸어도 걸어도
617             걸즈 앤 판처 극장판
677                    검사외전
684                    검우강호
686                  검은 사제들
691                    계춘할망
726    고녀석 맛나겠다2 : 함께라서 행복해
735                      고백
737              고산자, 대동여지도
790                 고스트버스터즈
...                     ...
15850               하드코어 헨리
15852                  하류인생
15854           하이큐!! 끝과 시작
15896          하이큐!! 승자와 패자
15935                   한공주
15936             한여름의 판타지아
15952        해리 포터와 죽음의 성물1
15959         해리가 샐리를 만났을 때
15981         해리포터와 죽음의 성물2
15988                  해바라기
15997                    해빙
16001                   해어화
16004                 핵소 고지
16024                행복한 사전
16025      향수 : 어느 살인자의 이야기
16029                 헤이트풀8
16032               헤일, 시저!
16033                     형
16101           형사; Duelist
16105   호두까기 인형: 장난감 왕국 대모험
16137             호두까기인형 3D
16138          호비와 동화나라 대모험
16174                  호우시절
16208                    혼숨
16245                  화양연화
16246                    화장
16248                    화차
16249                 환상의 빛
16309               후회하지 않아
16310                  히말라야

[641 rows x 1 columns]

In [55]:
mergemovie['개봉후일수']=pd.to_numeric(mergemovie['개봉후일수'], errors='coerce')
mergemovie=mergemovie.dropna()
mergemovie=mergemovie.where(mergemovie['개봉후일수']>=0).dropna()
mergemovie=mergemovie.where(mergemovie['개봉후일수']<14).dropna()
mergemovie

,영화명,누적관객수_x,개봉일,날짜,매출액점유율,관객수,누적관객수_y,개봉후일수
4,23 아이덴티티,1316094.0,2017-02-22,2017-02-22,0.237,137005.0,137279.0,0.0
5,23 아이덴티티,1316094.0,2017-02-22,2017-03-01,0.115,119402.0,1316094.0,7.0
6,23 아이덴티티,1316094.0,2017-02-22,2017-02-28,0.242,116555.0,1196692.0,6.0
7,23 아이덴티티,1316094.0,2017-02-22,2017-02-27,0.317,113233.0,1080137.0,5.0
8,23 아이덴티티,1316094.0,2017-02-22,2017-02-26,0.337,265101.0,966904.0,4.0
9,23 아이덴티티,1316094.0,2017-02-22,2017-02-25,0.341,283621.0,701803.0,3.0
10,23 아이덴티티,1316094.0,2017-02-22,2017-02-24,0.327,150119.0,418182.0,2.0
11,23 아이덴티티,1316094.0,2017-02-22,2017-02-23,0.306,130784.0,268063.0,1.0
173,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-15,0.017,6446.0,152504.0,6.0
174,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-14,0.057,19711.0,146058.0,5.0
175,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-13,0.055,16981.0,126347.0,4.0
176,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-12,0.030,27065.0,109366.0,3.0
177,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-11,0.034,31958.0,82301.0,2.0
178,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-10,0.056,25446.0,50343.0,1.0
179,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-09,0.060,24738.0,24897.0,0.0
180,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-22,0.003,1410.0,181941.0,13.0
181,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-21,0.012,3556.0,180531.0,12.0
182,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-20,0.012,3624.0,176975.0,11.0
183,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-19,0.006,5137.0,173351.0,10.0
184,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-18,0.007,6406.0,168214.0,9.0
185,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-17,0.011,4845.0,161808.0,8.0
186,50가지 그림자: 심연,188625.0,2017-02-09,2017-02-16,0.011,4459.0,156963.0,7.0
211,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-18,0.001,621.0,12090.0,6.0
212,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-17,0.003,883.0,11469.0,5.0
213,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-16,0.003,1147.0,10586.0,4.0
214,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-15,0.002,1936.0,9439.0,3.0
215,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-14,0.002,2072.0,7503.0,2.0
216,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-13,0.003,1324.0,5431.0,1.0
217,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-12,0.004,1424.0,4107.0,0.0
218,7년-그들이 없는 언론,16888.0,2017-01-12,2017-01-25,0.001,286.0,15460.0,13.0
...,...,...,...,...,...,...,...,...
16152,호비와 동화나라 대모험,16620.0,2016-12-08,2016-12-16,0.000,376.0,10984.0,8.0
16153,호비와 동화나라 대모험,16620.0,2016-12-08,2016-12-15,0.000,165.0,10608.0,7.0
16211,혼숨,288016.0,2016-10-26,2016-11-01,0.040,11197.0,207397.0,6.0
16212,혼숨,288016.0,2016-10-26,2016-10-31,0.042,13552.0,196200.0,5.0
16213,혼숨,288016.0,2016-10-26,2016-10-30,0.042,42689.0,182648.0,4.0
16214,혼숨,288016.0,2016-10-26,2016-10-29,0.043,52669.0,139959.0,3.0
16215,혼숨,288016.0,2016-10-26,2016-10-28,0.049,29867.0,87290.0,2.0
16216,혼숨,288016.0,2016-10-26,2016-10-27,0.055,23136.0,57423.0,1.0
16217,혼숨,288016.0,2016-10-26,2016-10-26,0.046,32837.0,34287.0,0.0
16218,혼숨,288016.0,2016-10-26,2016-11-08,0.021,4089.0,282054.0,13.0
16219,혼숨,288016.0,2016-10-26,2016-11-07,0.026,4937.0,277965.0,12.0
16220,혼숨,288016.0,2016-10-26,2016-11-06,0.024,16989.0,273028.0,11.0
16221,혼숨,288016.0,2016-10-26,2016-11-05,0.025,21319.0,256039.0,10.0
16222,혼숨,288016.0,2016-10-26,2016-11-04,0.027,9967.0,234720.0,9.0
16223,혼숨,288016.0,2016-10-26,2016-11-03,0.028,7318.0,224753.0,8.0
16224,혼숨,288016.0,2016-10-26,2016-11-02,0.038,10038.0,217435.0,7.0
16253,환상의 빛,19281.0,2016-07-07,2016-07-12,0.002,657.0,8169.0,5.0
16254,환상의 빛,19281.0,2016-07-07,2016-07-11,0.003,722.0,7512.0,4.0
16255,환상의 빛,19281.0,2016-07-07,2016-07-10,0.001,1232.0,6790.0,3.0
16256,환상의 빛,19281.0,2016-07-07,2016-07-09,0.001,1314.0,5558.0,2.0
16257,환상의 빛,19281.0,2016-07-07,2016-07-08,0.002,1069.0,4244.0,1.0
16258,환상의 빛,19281.0,2016-07-07,2016-07-07,0.003,974.0,3175.0,0.0
16260,환상의 빛,19281.0,2016-07-07,2016-07-19,0.001,496.0,12688.0,12.0
16261,환상의 빛,19281.0,2016-07-07,2016-07-18,0.001,429.0,12192.0,11.0
16262,환상의 빛,19281.0,2016-07-07,2016-07-17,0.001,926.0,11763.0,10.0
16263,환상의 빛,19281.0,2016-07-07,2016-07-16,0.001,876.0,10837.0,9.0
16264,환상의 빛,19281.0,2016-07-07,2016-07-15,0.001,534.0,9961.0,8.0
16265,환상의 빛,19281.0,2016-07-07,2016-07-14,0.002,614.0,9427.0,7.0
16266,환상의 빛,19281.0,2016-07-07,2016-07-13,0.002,644.0,8813.0,6.0
16273,환상의 빛,19281.0,2016-07-07,2016-07-20,0.000,477.0,13165.0,13.0

In [56]:
movie_name=pd.DataFrame(mergemovie['영화명'])
movie_name=movie_name.drop_duplicates()
movie_name

                                      영화명
4                                23 아이덴티티
173                          50가지 그림자: 심연
211                          7년-그들이 없는 언론
275                                가려진 시간
339                               감바의 대모험
407                    갤럭시 히어로즈: 라쳇 앤 클랭크
450                             거울나라의 앨리스
507                                   걷기왕
623                           걸즈 앤 판처 극장판
697                                  계춘할망
746                            고산자, 대동여지도
792                               고스트버스터즈
895                                    공조
956                                국가대표 2
1058                               굿바이 싱글
1181                               그래, 가족
1199                                그랜드파더
1271                               그레이트 월
1290                                   그물
1394             극장판 도라에몽: 신 진구의 버스 오브 재팬
1420                극장판 빰바라빤쮸: 바나나 왕국의 비밀
1431              극장판 소드 아트 온라인 -오디널 스케일-
1487           극장판 요괴워치: 염라대왕과 5개의 이야기다냥!
1530             극장판 유희왕 더 다크 사이드 오브 디멘션즈
1560   극장판 파워레인저: 닌자포스 VS 트레인포스 닌자 인 원더랜드
1632             극장판 프리파라 모두 모여라! 프리즘☆투어즈
1726                          나, 다니엘 블레이크
1819                           나우 유 씨 미 2
1878                              나의 산티아고
1997                            나의 살던 고향은
...                                   ...
14305                    키즈모노가타리 II : 열혈편
14336                      키코리키: 황금모자의 비밀
14367                            킹 오브 프리즘
14633                            태풍이 지나가고
14750                                  터널
14833                    터닝메카드W: 블랙미러의 부활
14885                           테일 오브 테일즈
14933             토마스와 친구들: 용감한 기관차와 괴물소동
14985                                  트롤
15004                                 트루스
15037                          트리플 엑스 리턴즈
15062                                  트릭
15100                       특별수사: 사형수의 편지
15184           파워배틀 와치카 미니카 배틀리그: 불꽃의 질주
15303                                 판도라
15369                                패신저스
15427                              퍼스널 쇼퍼
15498     포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」
15565                             플래그 더 문
15630                                플로렌스
15794                             피터와 드래곤
15854                         하이큐!! 끝과 시작
15896                        하이큐!! 승자와 패자
15998                                  해빙
16010                               핵소 고지
16041                                   형
16106                 호두까기 인형: 장난감 왕국 대모험
16140                        호비와 동화나라 대모험
16211                                  혼숨
16253                               환상의 빛

[252 rows x 1 columns]

In [63]:
mergemovie['누적관객수_x']=pd.to_numeric(mergemovie['누적관객수_x'], errors='coerce')
mergemovie=mergemovie.dropna()
movie300=mergemovie.where(mergemovie['누적관객수_x']>=3000000).dropna()
movie50=mergemovie.where(mergemovie['누적관객수_x']<3000000).dropna()
movie50=mergemovie.where(mergemovie['누적관객수_x']>=500000).dropna()
movieextra=mergemovie.where(mergemovie['누적관객수_x']<500000).dropna()

In [64]:
movie300

,영화명,누적관객수_x,개봉일,날짜,매출액점유율,관객수,누적관객수_y,개봉후일수
895,공조,7813875.0,2017-01-18,2017-01-18,0.238,151845.0,166451.0,0.0
900,공조,7813875.0,2017-01-18,2017-01-25,0.309,193551.0,1621572.0,7.0
901,공조,7813875.0,2017-01-18,2017-01-24,0.315,135694.0,1428021.0,6.0
902,공조,7813875.0,2017-01-18,2017-01-23,0.328,138338.0,1292327.0,5.0
903,공조,7813875.0,2017-01-18,2017-01-22,0.280,352228.0,1153989.0,4.0
904,공조,7813875.0,2017-01-18,2017-01-21,0.264,333625.0,801761.0,3.0
905,공조,7813875.0,2017-01-18,2017-01-20,0.273,160116.0,468136.0,2.0
906,공조,7813875.0,2017-01-18,2017-01-19,0.254,141569.0,308020.0,1.0
908,공조,7813875.0,2017-01-18,2017-01-31,0.479,304016.0,4860129.0,13.0
909,공조,7813875.0,2017-01-18,2017-01-30,0.467,761071.0,4556113.0,12.0
910,공조,7813875.0,2017-01-18,2017-01-29,0.471,797994.0,3795042.0,11.0
911,공조,7813875.0,2017-01-18,2017-01-28,0.478,664830.0,2997048.0,10.0
912,공조,7813875.0,2017-01-18,2017-01-27,0.426,472221.0,2332218.0,9.0
913,공조,7813875.0,2017-01-18,2017-01-26,0.355,238425.0,1859997.0,8.0
1819,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-19,0.475,161256.0,2063171.0,6.0
1820,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-18,0.492,164190.0,1901915.0,5.0
1821,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-17,0.362,419908.0,1737725.0,4.0
1822,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-16,0.360,462551.0,1317817.0,3.0
1823,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-15,0.361,197578.0,855266.0,2.0
1824,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-14,0.437,158284.0,657688.0,1.0
1825,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-13,0.465,196279.0,499404.0,0.0
1826,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-26,0.112,72088.0,2864992.0,13.0
1827,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-25,0.106,75854.0,2792904.0,12.0
1828,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-24,0.100,165431.0,2717050.0,11.0
1829,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-23,0.102,178378.0,2551619.0,10.0
1830,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-22,0.116,112697.0,2373241.0,9.0
1831,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-21,0.112,94499.0,2260544.0,8.0
1832,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-20,0.097,102874.0,2166045.0,7.0
2380,너의 이름은.,3645568.0,2017-01-04,2017-01-04,0.248,138028.0,212267.0,0.0
2385,너의 이름은.,3645568.0,2017-01-04,2017-01-11,0.334,140350.0,1628364.0,7.0
...,...,...,...,...,...,...,...,...
12438,인천상륙작전,7049854.0,2016-07-27,2016-08-04,0.202,263094.0,4167073.0,8.0
12439,인천상륙작전,7049854.0,2016-07-27,2016-08-03,0.200,319553.0,3903979.0,7.0
14750,터널,7120508.0,2016-08-10,2016-08-16,0.403,269940.0,3533426.0,6.0
14751,터널,7120508.0,2016-08-10,2016-08-15,0.380,681454.0,3263486.0,5.0
14752,터널,7120508.0,2016-08-10,2016-08-14,0.398,738317.0,2582032.0,4.0
14753,터널,7120508.0,2016-08-10,2016-08-13,0.399,675023.0,1843715.0,3.0
14754,터널,7120508.0,2016-08-10,2016-08-12,0.404,408520.0,1168692.0,2.0
14755,터널,7120508.0,2016-08-10,2016-08-11,0.392,360239.0,760172.0,1.0
14756,터널,7120508.0,2016-08-10,2016-08-10,0.393,379079.0,399933.0,0.0
14757,터널,7120508.0,2016-08-10,2016-08-23,0.360,136908.0,5377845.0,13.0
14758,터널,7120508.0,2016-08-10,2016-08-22,0.374,155416.0,5240937.0,12.0
14759,터널,7120508.0,2016-08-10,2016-08-21,0.371,428648.0,5085521.0,11.0
14760,터널,7120508.0,2016-08-10,2016-08-20,0.370,463615.0,4656873.0,10.0
14761,터널,7120508.0,2016-08-10,2016-08-19,0.356,227431.0,4193258.0,9.0
14762,터널,7120508.0,2016-08-10,2016-08-18,0.335,202170.0,3965827.0,8.0
14763,터널,7120508.0,2016-08-10,2016-08-17,0.362,230231.0,3763657.0,7.0
15303,판도라,4583273.0,2016-12-07,2016-12-07,0.424,154652.0,173024.0,0.0
15308,판도라,4583273.0,2016-12-07,2016-12-14,0.385,162153.0,1947524.0,7.0
15309,판도라,4583273.0,2016-12-07,2016-12-13,0.449,165775.0,1785371.0,6.0
15310,판도라,4583273.0,2016-12-07,2016-12-12,0.464,160345.0,1619596.0,5.0
15311,판도라,4583273.0,2016-12-07,2016-12-11,0.477,463151.0,1459251.0,4.0
15312,판도라,4583273.0,2016-12-07,2016-12-10,0.448,447707.0,996100.0,3.0
15313,판도라,4583273.0,2016-12-07,2016-12-09,0.424,210438.0,548393.0,2.0
15314,판도라,4583273.0,2016-12-07,2016-12-08,0.406,164931.0,337955.0,1.0
15316,판도라,4583273.0,2016-12-07,2016-12-20,0.355,135019.0,3381773.0,13.0
15317,판도라,4583273.0,2016-12-07,2016-12-19,0.381,133106.0,3246754.0,12.0
15318,판도라,4583273.0,2016-12-07,2016-12-18,0.441,394567.0,3113648.0,11.0
15319,판도라,4583273.0,2016-12-07,2016-12-17,0.430,401518.0,2719081.0,10.0
15320,판도라,4583273.0,2016-12-07,2016-12-16,0.399,210230.0,2317563.0,9.0
15321,판도라,4583273.0,2016-12-07,2016-12-15,0.373,159809.0,2107333.0,8.0

In [58]:
moviename300=pd.DataFrame(movie300['영화명'])
moviename300=moviename300.drop_duplicates()
moviename300

              영화명
895            공조
1819   나우 유 씨 미 2
2380      너의 이름은.
2970     닥터 스트레인지
3498          더 킹
3553         덕혜옹주
4180         라라랜드
4468           럭키
5078          마스터
6636           밀정
7636          부산행
9930     신비한 동물사전
10251         아가씨
12426      인천상륙작전
14750          터널
15303         판도라

In [59]:
moviename50=pd.DataFrame(movie50['영화명'])
moviename50=moviename50.drop_duplicates()
moviename50

                       영화명
4                 23 아이덴티티
275                 가려진 시간
450              거울나라의 앨리스
746             고산자, 대동여지도
792                고스트버스터즈
895                     공조
956                 국가대표 2
1058                굿바이 싱글
1819            나우 유 씨 미 2
2380               너의 이름은.
2970              닥터 스트레인지
3186          당신, 거기 있어줄래요
3498                   더 킹
3553                  덕혜옹주
3706               도리를 찾아서
4180                  라라랜드
4373                라이트 아웃
4468                    럭키
4601             레전드 오브 타잔
4631        레지던트 이블: 파멸의 날
4680        로그 원: 스타워즈 스토리
5078                   마스터
5229             마이펫의 이중생활
5417              매그니피센트 7
5579              맨 인 더 다크
5679             메카닉: 리크루트
5761        명탐정 코난: 순흑의 악몽
5838                   모아나
6160                미 비포 유
6454   미스 페레그린과 이상한 아이들의 집
...                    ...
9108          설리: 허드슨강의 기적
9296             수어사이드 스쿼드
9638              스타트렉 비욘드
9770                   스플릿
9930              신비한 동물사전
10046               싱 스트리트
10199                    씽
10251                  아가씨
10454                  아수라
10587      아이스 에이지: 지구 대충돌
10704           앵그리버드 더 무비
10975                 얼라이드
11155           엑스맨: 아포칼립스
11981        워크래프트: 전쟁의 서막
12259      인디펜던스 데이 : 리써전스
12426               인천상륙작전
12543                 인페르노
12893                   재심
12960         잭 리처: 네버 고 백
13020                  정글북
13070                제이슨 본
13134               조작된 도시
14090                컨저링 2
14151                  컨택트
14750                   터널
14985                   트롤
15100        특별수사: 사형수의 편지
15303                  판도라
15369                 패신저스
16041                    형

[67 rows x 1 columns]

In [60]:
movienameextra=pd.DataFrame(movieextra['영화명'])
movienameextra=movienameextra.drop_duplicates()
movienameextra

                                      영화명
173                          50가지 그림자: 심연
211                          7년-그들이 없는 언론
339                               감바의 대모험
407                    갤럭시 히어로즈: 라쳇 앤 클랭크
507                                   걷기왕
623                           걸즈 앤 판처 극장판
697                                  계춘할망
1181                               그래, 가족
1199                                그랜드파더
1271                               그레이트 월
1290                                   그물
1394             극장판 도라에몽: 신 진구의 버스 오브 재팬
1420                극장판 빰바라빤쮸: 바나나 왕국의 비밀
1431              극장판 소드 아트 온라인 -오디널 스케일-
1487           극장판 요괴워치: 염라대왕과 5개의 이야기다냥!
1530             극장판 유희왕 더 다크 사이드 오브 디멘션즈
1560   극장판 파워레인저: 닌자포스 VS 트레인포스 닌자 인 원더랜드
1632             극장판 프리파라 모두 모여라! 프리즘☆투어즈
1726                          나, 다니엘 블레이크
1878                              나의 산티아고
1997                            나의 살던 고향은
2137                        나의 위대한 친구, 세잔
2187                              나이스 가이즈
2218                        내 어깨 위 고양이, 밥
2355                                   너브
2505                             녹터널 애니멀스
2572                                   눈길
2580                  눈의 여왕 3: 눈과 불의 마법대결
2622                          뉴 스텝업: 어반댄스
2662                       닌자터틀 : 어둠의 히어로
...                                   ...
13800                                카페 6
13835                            카페 소사이어티
14021                             캡틴 판타스틱
14189                          쿠보와 전설의 악기
14233                                크리미널
14262                     키즈모노가타리 I : 철혈편
14305                    키즈모노가타리 II : 열혈편
14336                      키코리키: 황금모자의 비밀
14367                            킹 오브 프리즘
14633                            태풍이 지나가고
14833                    터닝메카드W: 블랙미러의 부활
14885                           테일 오브 테일즈
14933             토마스와 친구들: 용감한 기관차와 괴물소동
15004                                 트루스
15037                          트리플 엑스 리턴즈
15062                                  트릭
15184           파워배틀 와치카 미니카 배틀리그: 불꽃의 질주
15427                              퍼스널 쇼퍼
15498     포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」
15565                             플래그 더 문
15630                                플로렌스
15794                             피터와 드래곤
15854                         하이큐!! 끝과 시작
15896                        하이큐!! 승자와 패자
15998                                  해빙
16010                               핵소 고지
16106                 호두까기 인형: 장난감 왕국 대모험
16140                        호비와 동화나라 대모험
16211                                  혼숨
16253                               환상의 빛

[185 rows x 1 columns]

In [1]:
movie300['비율']=movie300['누적관객수_y']/movie300['누적관객수_x']
movie50['비율']=movie50['누적관객수_y']/movie50['누적관객수_x']
movieextra['비율']=movieextra['누적관객수_y']/movieextra['누적관객수_x']

NameError: name 'movie300' is not defined

In [84]:
movie300=movie300.dropna()
movie300_1=movie300.where(movie300['개봉후일수']<7).dropna()
movie300_2=movie300.where(movie300['개봉후일수']>=7).dropna()

movie50=movie50.dropna()
movie50_1=movie50.where(movie50['개봉후일수']<7).dropna()
movie50_2=movie50.where(movie50['개봉후일수']>=7).dropna()

movieextra=movieextra.dropna()
movieextra_1=movieextra.where(movieextra['개봉후일수']<7).dropna()
movieextra_2=movieextra.where(movieextra['개봉후일수']>=7).dropna()

In [77]:
movie300_1

,영화명,누적관객수_x,개봉일,날짜,매출액점유율,관객수,누적관객수_y,개봉후일수,비율
895,공조,7813875.0,2017-01-18,2017-01-18,0.238,151845.0,166451.0,0.0,0.021302
901,공조,7813875.0,2017-01-18,2017-01-24,0.315,135694.0,1428021.0,6.0,0.182755
902,공조,7813875.0,2017-01-18,2017-01-23,0.328,138338.0,1292327.0,5.0,0.165389
903,공조,7813875.0,2017-01-18,2017-01-22,0.280,352228.0,1153989.0,4.0,0.147685
904,공조,7813875.0,2017-01-18,2017-01-21,0.264,333625.0,801761.0,3.0,0.102607
905,공조,7813875.0,2017-01-18,2017-01-20,0.273,160116.0,468136.0,2.0,0.059911
906,공조,7813875.0,2017-01-18,2017-01-19,0.254,141569.0,308020.0,1.0,0.039420
1819,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-19,0.475,161256.0,2063171.0,6.0,0.665515
1820,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-18,0.492,164190.0,1901915.0,5.0,0.613499
1821,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-17,0.362,419908.0,1737725.0,4.0,0.560536
1822,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-16,0.360,462551.0,1317817.0,3.0,0.425087
1823,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-15,0.361,197578.0,855266.0,2.0,0.275882
1824,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-14,0.437,158284.0,657688.0,1.0,0.212150
1825,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-13,0.465,196279.0,499404.0,0.0,0.161092
2380,너의 이름은.,3645568.0,2017-01-04,2017-01-04,0.248,138028.0,212267.0,0.0,0.058226
2386,너의 이름은.,3645568.0,2017-01-04,2017-01-10,0.384,150768.0,1488014.0,6.0,0.408171
2387,너의 이름은.,3645568.0,2017-01-04,2017-01-09,0.412,154781.0,1337246.0,5.0,0.366814
2388,너의 이름은.,3645568.0,2017-01-04,2017-01-08,0.325,333008.0,1182465.0,4.0,0.324357
2389,너의 이름은.,3645568.0,2017-01-04,2017-01-07,0.307,335325.0,849457.0,3.0,0.233011
2390,너의 이름은.,3645568.0,2017-01-04,2017-01-06,0.307,169402.0,514132.0,2.0,0.141029
2391,너의 이름은.,3645568.0,2017-01-04,2017-01-05,0.265,132463.0,344730.0,1.0,0.094561
2970,닥터 스트레인지,5446379.0,2016-10-26,2016-11-01,0.566,143117.0,2711347.0,6.0,0.497826
2971,닥터 스트레인지,5446379.0,2016-10-26,2016-10-31,0.580,168858.0,2568230.0,5.0,0.471548
2972,닥터 스트레인지,5446379.0,2016-10-26,2016-10-30,0.631,584286.0,2399372.0,4.0,0.440544
2973,닥터 스트레인지,5446379.0,2016-10-26,2016-10-29,0.643,692976.0,1815086.0,3.0,0.333265
2974,닥터 스트레인지,5446379.0,2016-10-26,2016-10-28,0.621,340045.0,1122110.0,2.0,0.206029
2975,닥터 스트레인지,5446379.0,2016-10-26,2016-10-27,0.603,228451.0,782065.0,1.0,0.143594
2976,닥터 스트레인지,5446379.0,2016-10-26,2016-10-26,0.639,435068.0,553614.0,0.0,0.101648
3498,더 킹,5315909.0,2017-01-18,2017-01-18,0.457,288966.0,302978.0,0.0,0.056995
3505,더 킹,5315909.0,2017-01-18,2017-01-24,0.367,156749.0,2173139.0,6.0,0.408799
...,...,...,...,...,...,...,...,...,...
9935,신비한 동물사전,4667176.0,2016-11-16,2016-11-17,0.605,274088.0,519347.0,1.0,0.111276
9936,신비한 동물사전,4667176.0,2016-11-16,2016-11-16,0.570,242775.0,245259.0,0.0,0.052550
10251,아가씨,4288255.0,2016-06-01,2016-06-07,0.508,146895.0,2367281.0,6.0,0.552038
10252,아가씨,4288255.0,2016-06-01,2016-06-06,0.394,395072.0,2220386.0,5.0,0.517783
10253,아가씨,4288255.0,2016-06-01,2016-06-05,0.434,470236.0,1825314.0,4.0,0.425654
10254,아가씨,4288255.0,2016-06-01,2016-06-04,0.465,481442.0,1355078.0,3.0,0.315998
10255,아가씨,4288255.0,2016-06-01,2016-06-03,0.551,312873.0,873636.0,2.0,0.203728
10256,아가씨,4288255.0,2016-06-01,2016-06-02,0.569,259971.0,560763.0,1.0,0.130767
10257,아가씨,4288255.0,2016-06-01,2016-06-01,0.606,290024.0,300792.0,0.0,0.070143
12426,인천상륙작전,7049854.0,2016-07-27,2016-08-02,0.406,462324.0,3584426.0,6.0,0.508440
12427,인천상륙작전,7049854.0,2016-07-27,2016-08-01,0.401,495531.0,3122102.0,5.0,0.442861
12428,인천상륙작전,7049854.0,2016-07-27,2016-07-31,0.381,697945.0,2626571.0,4.0,0.372571
12429,인천상륙작전,7049854.0,2016-07-27,2016-07-30,0.359,691478.0,1928626.0,3.0,0.273570
12430,인천상륙작전,7049854.0,2016-07-27,2016-07-29,0.351,405477.0,1237148.0,2.0,0.175486
12431,인천상륙작전,7049854.0,2016-07-27,2016-07-28,0.340,354500.0,831671.0,1.0,0.117970
12432,인천상륙작전,7049854.0,2016-07-27,2016-07-27,0.337,464460.0,477171.0,0.0,0.067685
14750,터널,7120508.0,2016-08-10,2016-08-16,0.403,269940.0,3533426.0,6.0,0.496232
14751,터널,7120508.0,2016-08-10,2016-08-15,0.380,681454.0,3263486.0,5.0,0.458322
14752,터널,7120508.0,2016-08-10,2016-08-14,0.398,738317.0,2582032.0,4.0,0.362619
14753,터널,7120508.0,2016-08-10,2016-08-13,0.399,675023.0,1843715.0,3.0,0.258930
14754,터널,7120508.0,2016-08-10,2016-08-12,0.404,408520.0,1168692.0,2.0,0.164130
14755,터널,7120508.0,2016-08-10,2016-08-11,0.392,360239.0,760172.0,1.0,0.106758
14756,터널,7120508.0,2016-08-10,2016-08-10,0.393,379079.0,399933.0,0.0,0.056166
15303,판도라,4583273.0,2016-12-07,2016-12-07,0.424,154652.0,173024.0,0.0,0.037751
15309,판도라,4583273.0,2016-12-07,2016-12-13,0.449,165775.0,1785371.0,6.0,0.389541
15310,판도라,4583273.0,2016-12-07,2016-12-12,0.464,160345.0,1619596.0,5.0,0.353371
15311,판도라,4583273.0,2016-12-07,2016-12-11,0.477,463151.0,1459251.0,4.0,0.318386
15312,판도라,4583273.0,2016-12-07,2016-12-10,0.448,447707.0,996100.0,3.0,0.217334
15313,판도라,4583273.0,2016-12-07,2016-12-09,0.424,210438.0,548393.0,2.0,0.119651
15314,판도라,4583273.0,2016-12-07,2016-12-08,0.406,164931.0,337955.0,1.0,0.073737

In [78]:
movie300_2

,영화명,누적관객수_x,개봉일,날짜,매출액점유율,관객수,누적관객수_y,개봉후일수,비율
900,공조,7813875.0,2017-01-18,2017-01-25,0.309,193551.0,1621572.0,7.0,0.207525
908,공조,7813875.0,2017-01-18,2017-01-31,0.479,304016.0,4860129.0,13.0,0.621987
909,공조,7813875.0,2017-01-18,2017-01-30,0.467,761071.0,4556113.0,12.0,0.583080
910,공조,7813875.0,2017-01-18,2017-01-29,0.471,797994.0,3795042.0,11.0,0.485680
911,공조,7813875.0,2017-01-18,2017-01-28,0.478,664830.0,2997048.0,10.0,0.383555
912,공조,7813875.0,2017-01-18,2017-01-27,0.426,472221.0,2332218.0,9.0,0.298471
913,공조,7813875.0,2017-01-18,2017-01-26,0.355,238425.0,1859997.0,8.0,0.238038
1826,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-26,0.112,72088.0,2864992.0,13.0,0.924157
1827,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-25,0.106,75854.0,2792904.0,12.0,0.900904
1828,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-24,0.100,165431.0,2717050.0,11.0,0.876436
1829,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-23,0.102,178378.0,2551619.0,10.0,0.823073
1830,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-22,0.116,112697.0,2373241.0,9.0,0.765534
1831,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-21,0.112,94499.0,2260544.0,8.0,0.729181
1832,나우 유 씨 미 2,3100113.0,2016-07-13,2016-07-20,0.097,102874.0,2166045.0,7.0,0.698699
2385,너의 이름은.,3645568.0,2017-01-04,2017-01-11,0.334,140350.0,1628364.0,7.0,0.446669
2393,너의 이름은.,3645568.0,2017-01-04,2017-01-17,0.283,93300.0,2680231.0,13.0,0.735203
2394,너의 이름은.,3645568.0,2017-01-04,2017-01-16,0.311,97566.0,2586931.0,12.0,0.709610
2395,너의 이름은.,3645568.0,2017-01-04,2017-01-15,0.305,298280.0,2489365.0,11.0,0.682847
2396,너의 이름은.,3645568.0,2017-01-04,2017-01-14,0.292,292247.0,2191085.0,10.0,0.601027
2397,너의 이름은.,3645568.0,2017-01-04,2017-01-13,0.319,148996.0,1898838.0,9.0,0.520862
2398,너의 이름은.,3645568.0,2017-01-04,2017-01-12,0.290,121478.0,1749842.0,8.0,0.479992
2977,닥터 스트레인지,5446379.0,2016-10-26,2016-11-08,0.466,80183.0,4134668.0,13.0,0.759159
2978,닥터 스트레인지,5446379.0,2016-10-26,2016-11-07,0.509,88046.0,4054485.0,12.0,0.744437
2979,닥터 스트레인지,5446379.0,2016-10-26,2016-11-06,0.577,368054.0,3966439.0,11.0,0.728271
2980,닥터 스트레인지,5446379.0,2016-10-26,2016-11-05,0.599,441949.0,3598385.0,10.0,0.660693
2981,닥터 스트레인지,5446379.0,2016-10-26,2016-11-04,0.574,192189.0,3156436.0,9.0,0.579548
2982,닥터 스트레인지,5446379.0,2016-10-26,2016-11-03,0.523,121481.0,2964247.0,8.0,0.544260
2983,닥터 스트레인지,5446379.0,2016-10-26,2016-11-02,0.549,131419.0,2842766.0,7.0,0.521955
3504,더 킹,5315909.0,2017-01-18,2017-01-25,0.317,199750.0,2372889.0,7.0,0.446375
3512,더 킹,5315909.0,2017-01-18,2017-01-31,0.229,144575.0,4410130.0,13.0,0.829610
...,...,...,...,...,...,...,...,...,...
9942,신비한 동물사전,4667176.0,2016-11-16,2016-11-24,0.364,118637.0,2497901.0,8.0,0.535206
9943,신비한 동물사전,4667176.0,2016-11-16,2016-11-23,0.482,140647.0,2379264.0,7.0,0.509787
10258,아가씨,4288255.0,2016-06-01,2016-06-14,0.234,74710.0,3288831.0,13.0,0.766939
10259,아가씨,4288255.0,2016-06-01,2016-06-13,0.225,76700.0,3214121.0,12.0,0.749517
10260,아가씨,4288255.0,2016-06-01,2016-06-12,0.163,178490.0,3137421.0,11.0,0.731631
10261,아가씨,4288255.0,2016-06-01,2016-06-11,0.191,215487.0,2958931.0,10.0,0.690008
10262,아가씨,4288255.0,2016-06-01,2016-06-10,0.237,132708.0,2743444.0,9.0,0.639758
10263,아가씨,4288255.0,2016-06-01,2016-06-09,0.228,106905.0,2610736.0,8.0,0.608811
10264,아가씨,4288255.0,2016-06-01,2016-06-08,0.498,136550.0,2503831.0,7.0,0.583881
12433,인천상륙작전,7049854.0,2016-07-27,2016-08-09,0.182,150546.0,5565410.0,13.0,0.789436
12434,인천상륙작전,7049854.0,2016-07-27,2016-08-08,0.194,169310.0,5414864.0,12.0,0.768082
12435,인천상륙작전,7049854.0,2016-07-27,2016-08-07,0.226,391895.0,5245554.0,11.0,0.744066
12436,인천상륙작전,7049854.0,2016-07-27,2016-08-06,0.222,413581.0,4853659.0,10.0,0.688477
12437,인천상륙작전,7049854.0,2016-07-27,2016-08-05,0.212,273005.0,4440078.0,9.0,0.629811
12438,인천상륙작전,7049854.0,2016-07-27,2016-08-04,0.202,263094.0,4167073.0,8.0,0.591086
12439,인천상륙작전,7049854.0,2016-07-27,2016-08-03,0.200,319553.0,3903979.0,7.0,0.553767
14757,터널,7120508.0,2016-08-10,2016-08-23,0.360,136908.0,5377845.0,13.0,0.755261
14758,터널,7120508.0,2016-08-10,2016-08-22,0.374,155416.0,5240937.0,12.0,0.736034
14759,터널,7120508.0,2016-08-10,2016-08-21,0.371,428648.0,5085521.0,11.0,0.714208
14760,터널,7120508.0,2016-08-10,2016-08-20,0.370,463615.0,4656873.0,10.0,0.654009
14761,터널,7120508.0,2016-08-10,2016-08-19,0.356,227431.0,4193258.0,9.0,0.588899
14762,터널,7120508.0,2016-08-10,2016-08-18,0.335,202170.0,3965827.0,8.0,0.556958
14763,터널,7120508.0,2016-08-10,2016-08-17,0.362,230231.0,3763657.0,7.0,0.528566
15308,판도라,4583273.0,2016-12-07,2016-12-14,0.385,162153.0,1947524.0,7.0,0.424920
15316,판도라,4583273.0,2016-12-07,2016-12-20,0.355,135019.0,3381773.0,13.0,0.737851
15317,판도라,4583273.0,2016-12-07,2016-12-19,0.381,133106.0,3246754.0,12.0,0.708392
15318,판도라,4583273.0,2016-12-07,2016-12-18,0.441,394567.0,3113648.0,11.0,0.679350
15319,판도라,4583273.0,2016-12-07,2016-12-17,0.430,401518.0,2719081.0,10.0,0.593262
15320,판도라,4583273.0,2016-12-07,2016-12-16,0.399,210230.0,2317563.0,9.0,0.505657
15321,판도라,4583273.0,2016-12-07,2016-12-15,0.373,159809.0,2107333.0,8.0,0.459788

In [81]:
sum(movie300_1['비율'])/len(movie300_1)

0.25736532034895937

In [82]:
sum(movie300_2['비율'])/len(movie300_2)

0.61763697823732877

In [85]:
sum(movie50_1['비율'])/len(movie50_1)

0.35613867634694241

In [86]:
sum(movie50_2['비율'])/len(movie50_2)

0.74942747260512999

In [87]:
sum(movieextra_1['비율'])/len(movieextra_1)

0.4622428140230096

In [88]:
sum(movieextra_2['비율'])/len(movieextra_2)

0.808579257039438

In [89]:
(sum(movie300_2['비율'])/len(movie300_2))/(sum(movie300_1['비율'])/len(movie300_1))

2.3998453925333849

In [90]:
(sum(movie50_2['비율'])/len(movie50_2))/(sum(movie50_1['비율'])/len(movie50_1))

2.1043136350488774

In [91]:
(sum(movieextra_2['비율'])/len(movieextra_2))/(sum(movieextra_1['비율'])/len(movieextra_1))

1.7492521949712525

In [92]:
movie300.to_csv('movie300만이상.csv')

In [93]:
movie50.to_csv('movie50만이상.csv')

In [94]:
movieextra.to_csv('movie50만이하.csv')

In [97]:
movie300mean=pd.DataFrame(movie300['매출액점유율'].groupby(movie300['개봉후일수']).mean())
movie50mean=pd.DataFrame(movie50['매출액점유율'].groupby(movie50['개봉후일수']).mean())
movieextramean=pd.DataFrame(movieextra['매출액점유율'].groupby(movieextra['개봉후일수']).mean())

In [98]:
movie300mean

         매출액점유율
개봉후일수
0.0    0.464000
1.0    0.467000
2.0    0.477688
3.0    0.467812
4.0    0.470625
5.0    0.477375
6.0    0.465687
7.0    0.362437
8.0    0.336813
9.0    0.357063
10.0   0.363563
11.0   0.354563
12.0   0.328750
13.0   0.302312

In [100]:
movie300mean.to_csv('300그래프.csv')
movie50mean.to_csv('50그래프.csv')
movieextramean.to_csv('extra그래프.csv')